export const DADOS_CADASTRAIS = {
  SALVAR_TELA_INICIAL: 'DADOS_CADASTRAIS.SALVAR_TELA_INICIAL',
  SALVAR_INFORMACOES_ADICIONAIS: 'DADOS_CADASTRAIS.SALVAR_INFORMACOES_ADICIONAIS',
  LIMPAR: 'DADOS_CADASTRAIS.LIMPAR',
};
